---
abstract: 'Add useful objects to your templates'
author:
  - 'Rhesa Rozendaal <rhesa@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300016, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-Template-Plugin-Dot-Helpers
requires:
  HTML::Template::Pluggable: 0.12
  HTML::Template::Plugin::Dot: 0.96
  Number::Format: 0
  Test::More: 0
resources:
  repository: http://github.com/rhesa/html-template-plugin-dot-helpers
version: 0.06
